# Generated by Django 3.1.1 on 2020-12-07 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djnews', '0002_newsarticle_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
