# Generated by Django 3.0.3 on 2020-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnews', '0005_auto_20201203_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
